language: crystal
script:
- crystal tool format --check
deploy:
  provider: releases
  edge: true
  file: bin/put-io
  username: plambert
  on:
    tags: true
  token:
    secure: C0+RF0gwn2zaF3A4XO5DyvZASAJZ9jvG+0gpdl5KeEUlwVVNwQd2EtN1XQFfNRmD1tak8Ym5vuBaIfhB+gPqP10vz/P1AwmhBio8vwZjovRb3VKRA0SUQnHzUqM6HPk9T/AbP/5l3wYJfO/rvse/7khSbcZpJJZYBYy4U9pgjuTEOHm4qYgI8tipCmJVJsBNuPMpCTFiIMV7Xs5jnL2oL/HQFC6JCdxpvxVcSiY03bjM6aKiz4P9cxj18C+D6jlStcRIGuF+F2EhCm+5lPl3EqYpXylMo7/6sM9Ooi3l1XO94xRwmhaPFv7gm0Yu8mcT4+dRwgrVns9P1O1ulRORbQeweUKFZFYixF/NVrjcbewqJit8S96w0cg5+Rp9NoiiNrNHbnQ2OX+EVi09kuUGLHWlFvRC9nDKYA/1JW6AExpiT/yJXyYkilFQD1Adbw8VtrBUSArsxMeHk29DQj6dHrxIiy+H9gkBmG79gDhR8ZraL+ArcfwbwUGL7+1SlEGkBGcb4yWSMRcNMRhjAQdpsd3jN0eUxJJWEMmgOvbTVeJZ+0EPapvGABVTm0u2Wk0rbc6/tO1PcCjvxue9FGzfbJbV8tCOxOL4T4cJ7Gvp7bll1koPqdGoQdhZuMdd5zf058mLp8GzpyGh6F/6zmrHFnm5uqP7NPvHymcR5NRCbPg=
